backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use common\models\LoginForm;
use Yii;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
                'layout' => Yii::$app->user->identity ? 'admin' : 'admin',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string|Response
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = 'blank';

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use backend\models\ApplicationsSearch;
use backend\models\Applications;
use backend\models\JobsSearch;
use backend\models\Jobs;
use backend\models\FormFields;
use backend\models\FormFieldsData;
use yii\web\UploadedFile;
use backend\models\FileUpload;
use backend\models\Applicants;
use backend\models\Users;

/**
** Site controller
**/

class SiteController extends Controller
{
    /**
    ** {@inheritdoc}
    **/

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup','apply','profile','update'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout','apply','profile','update'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new JobsSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);
        return $this->render('index',['dataProvider'=>$dataProvider,'searchModel'=>$searchModel]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }        

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        }

        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->setFlash('success', 'Thank you for registration. Please check your inbox for verification email.');
            return $this->redirect(['login']);
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            }

            Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
    */

    public function actionResetPassword($token) {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @throws BadRequestHttpException
     * @return yii\web\Response
     */
    
    public function actionVerifyEmail($token) {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if (($user = $model->verifyEmail()) && Yii::$app->user->login($user)) {
            Yii::$app->session->setFlash('success', 'Your email has been confirmed!');
            return $this->goHome();
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    /**
     * Resend verification email
     *
     * @return mixed
    */

    public function actionResendVerificationEmail() {
        $model = new ResendVerificationEmailForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            }
            Yii::$app->session->setFlash('error', 'Sorry, we are unable to resend verification email for the provided email address.');
        }

        return $this->render('resendVerificationEmail', [
            'model' => $model
        ]);
    }

    public function actionJob($id) {
        $model = Jobs::findOne(['status'=>1,'job_id'=>$id]);
        $application = new Applications();
        if(Yii::$app->user->identity){
           $applicant = Applicants::findOne(['user_id'=>Yii::$app->user->identity->user_id]);
            $application = Applications::findOne(['applicant_id'=>$applicant->applicant_id,'job_id'=>$id]);
            if(!$application){
                $application = new Applications();
            } 
        }
        
        if($model) {
            return $this->render('job',[
                'model'=>$model,
                'application'=>$application
            ]);
        }
    }

    public function actionApply($id) {
        $model = Jobs::findOne(['status'=>1,'job_id'=>$id]);
        if($model) {
            $applicant = Applicants::findOne(['user_id'=>Yii::$app->user->identity->user_id]);
            $application = Applications::findOne(['applicant_id'=>$applicant->applicant_id,'job_id'=>$id]);
            if(!$application){
                $application = new Applications();
            }
            $FormFields = FormFields::find()->where(['job_id'=>$id,'Step'=>1])->all();
            if(Yii::$app->request->post()) {
                $application->load(Yii::$app->request->post());
                $application->job_id = $id;
                $application->applicant_id = $applicant->applicant_id;
                $application->status_id = 1;
                
                $FileUpload = new FileUpload();
                $FileUpload->load(Yii::$app->request->post(),"");
                $FileUpload->UploadFile = UploadedFile::getInstanceByName("cv");
                $application->cv = $FileUpload->upload();

                $FileUpload->UploadFile = UploadedFile::getInstanceByName("cover_letter");
                $application->cover_letter = $FileUpload->upload();
                
                if($application->save()) {
                    $this->saveData([
                        'FormFields'=>$FormFields,
                        'job_id'=>$id,
                        'application_id'=>$application->application_id
                    ]);
                    return $this->redirect(['profile','submitted'=>1]);
                }
            }else{
                return $this->render('apply',[
                    'model'=>$model,
                    'application'=>$application,
                    'FormFields'=>$FormFields
                ]);
            }
        }
    }

    public function saveData($params){
        $FormFields = $params['FormFields'];
        $data = Yii::$app->request->post();

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/applicationForm.php
<?php if($FormFields): foreach($FormFields as $Field): ?>
	<?php $Required = $Field->Required ? "required" : NULL; ?>
	<!-- textbox -->
	<?php if($Field->Type == 'textbox'):?>
		<div class="form-group">
			<label><?=$Field->Label?></label>
			<input data-validation="<?=$Field->Validation." ".$Required?>" placeholder="" name="<?=$Field->FormFieldID?>" class="form-control">
		</div>
	<?php endif;?>
	<!-- date -->
	<?php if($Field->Type == 'date'):?>
		<div class="form-group">
			<label><?=$Field->Label?></label>
			<input data-validation="<?=$Field->Validation." ".$Required?>" placeholder="" type="date" name="<?=$Field->FormFieldID?>" class="form-control">
		</div>
	<?php endif;?>
	<!-- textarea -->
	<?php if($Field->Type == 'textarea'):?>
		<div class="form-group">
			<label><?=$Field->Label?></label>
			<textarea data-validation="<?=$Field->Validation." ".$Required?>" placeholder="" name="<?=$Field->FormFieldID?>" class="form-control"></textarea>
		</div>
	<?php endif;?>
	<!-- dropdown -->
	<?php if($Field->Type == 'dropdown'):?>
		<?php $options = explode('|',$Field->Options);?>
		<div class="form-group">
			<label><?=$Field->Label?></label>
			<select data-validation="<?=$Field->Validation." ".$Required?>" name="<?=$Field->FormFieldID?>" class="form-control">
				<option value="">Select</option>
				<?php if($options): foreach($options as $option):?>
					<?php $parts = explode(':', $option); ?>
					<option value="<?=trim($parts[0])?>"><?=trim($parts[1])?></option>
				<?php endforeach;endif;?>
			</select>
		</div>
	<?php endif;?>
	<!-- file -->
	<?php if($Field->Type == 'file'):?>
		<div class="form-group">
			<label><?=$Field->Label?></label><br>
			<input accept=".pdf,.png,.jpeg,.jpg,.gif" type="file" data-validation="<?=$Field->Validation." ".$Required?>" placeholder="" name="<?=$Field->FormFieldID?>">
		</div>
	<?php endif;?>
<?php endforeach;endif;?>

frontend/views/site/apply.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;
$this->title = $model->title;
\yii\web\YiiAsset::register($this);
use yii\widgets\ActiveForm;
?>
<div class="row">
	<div class="col-md-4">
		<div class="boxed">
			<?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    ['attribute'=>'title','label'=>'Job'],
                    'deadline:date',
                ],
            ]) ?>
		</div>
		<br>
	</div>
	<div class="col-md-8">
		<div class="boxed">
			<?php $form = ActiveForm::begin();?>
				<?=$this->render('applicationForm',['FormFields' => $FormFields]);?>
				<label>Upload CV</label>
				<?=$form->field($application,'cv')->fileInput(['name'=>'cv'])->label(false);?>
				<hr class="hr-20">
				<label>Upload Cover Letter</label>
				<?=$form->field($application,'cover_letter')->fileInput(['name'=>'cover_letter'])->label(false);?>
				<hr class="hr-20">
				<div class="form-group float-right">
	                <?= Html::submitButton('Submit', ['class' => 'btn btn-primary btn-sm']) ?>
	            </div>
	            <span class="clearfix"></span>
			<?php ActiveForm::end();?>
		</div>
	</div>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php
$this->title = Yii::$app->name;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
?>
<div class="row">
	<div class="col-md-3">
		<div class="boxed">
			<div class="jobs-search">

			    <?php $form = ActiveForm::begin(['action' => ['index'],'method' => 'get']); ?>

			    <?= $form->field($searchModel, 'title')->textInput(['placeholder'=>'Search by title'])->label('Job') ?>

			    <?=$form->field($searchModel,'industry_id')->widget(Select2::classname(), 
			        [
			            'data' => ArrayHelper::map(backend\models\Industries::find()->all(),'industry_id','name'),
			            'options' => ['placeholder' => 'Select'],
			            'pluginOptions' => [
			                'allowClear' => true
			            ],
			        ]
			    )->label('Industry'); ?>

			    <?=$form->field($searchModel,'country_id')->widget(Select2::classname(), 
			        [
			            'data' => ArrayHelper::map(backend\models\Countries::find()->all(),'country_id','nicename'),
			            'options' => ['placeholder' => 'Select'],
			            'pluginOptions' => [
			                'allowClear' => true
			            ],
			        ]
			    )->label('Country'); ?>

			    <div class="form-group">
			        <?= Html::submitButton('Search', ['class' => 'btn btn-primary btn-sm col-md-12']) ?>
			    </div>

			    <?php ActiveForm::end(); ?>

			</div>
		</div>
		<br>
	</div>
	<div class="col-md-9">
		<div class="boxed table-responsive">
			<?= GridView::widget([
	            'dataProvider' => $dataProvider,
	            // 'filterModel' => $searchModel,
	            'columns' => [
	                ['class' => 'yii\grid\SerialColumn'],

	                ['attribute'=>'title','label'=>'Job','format'=>'raw','value'=>function($model){
	                	return Html::a($model->title,['site/job','id'=>$model->job_id],['style'=>'color:#03172D;font-weight:500']);
	                }],
	                ['attribute'=>'company.name','label'=>'Company'],
	                ['attribute'=>'country.nicename','label'=>'Country'],
	                'deadline:date',
	                [
	                    'class' => ActionColumn::className(),
	                    'urlCreator' => function ($action, backend\models\Jobs $model, $key, $index, $column) {
	                        return Url::toRoute(['job', 'id' => $model->job_id]);
	                    },
	                    'template' => '{view}'
	                ],
	            ],
	        ]); ?>
	    </div>
	</div>
</div>

frontend/views/site/job.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;
$this->title = $model->title;
\yii\web\YiiAsset::register($this);
?>
<div class="page-wrapper">
    <div class="boxed">
        <div class="page-header">
            <div class="float-left">
                <h5><?=$this->title?></h5>
            </div>
            <div class="float-right">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <?= Html::a('Jobs', ['/'], ['class' => 'btn btn-secondary btn-sm text-muted']) ?>
                        <?= !$application->application_id ? Html::a('Apply', ['apply', 'id' => $model->job_id], ['class' => 'btn btn-primary btn-sm']) : NULL ?>
                    </li>
                </ul>
            </div>
            <span class="clearfix"></span>
        </div>
        <div class="page-content">
            <div class="jobs-view">

                <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        'title',
                        ['attribute'=>'company.name','label'=>'Company'],
                        ['attribute'=>'industry.name','label'=>'Industry'],
                        'description:html',
                        'requirements:html',
                        'responsibilities:html',
                        'seniority',
                        ['attribute'=>'country.nicename','label'=>'Country'],
                        'deadline:date',
                    ],
                ]) ?>

            </div>
        </div>
    </div>
</div>

frontend/views/site/login.php
<?php
    use yii\bootstrap4\Html;
    use yii\bootstrap4\ActiveForm;
    $this->title = 'Login';
    $this->params['breadcrumbs'][] = $this->title;
?>
<div class="col-lg-6 offset-lg-3">
    <div class="site-login boxed">
        <h5><?= Html::encode($this->title) ?></h5>
        <hr class="hr-20">
        <p>Please fill out the following fields to login:</p>
        <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
            <?= $form->field($model, 'email')->textInput() ?>
            <?= $form->field($model, 'password')->passwordInput() ?>
            <?= $form->field($model, 'rememberMe')->checkbox() ?>
            <div style="color:#999;margin:1em 0">
                Don't have an account? <?= Html::a('Register', ['site/signup']) ?>
                <br>
                Forgot your password? <?= Html::a('Reset', ['site/request-password-reset']) ?>
                <br>
                New verification email? <?= Html::a('Resend', ['site/resend-verification-email']) ?>
            </div>
            <hr class="hr-20">
            <div class="form-group float-right">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary btn-sm', 'name' => 'login-button']) ?>
            </div>
            <span class="clearfix"></span>
        <?php ActiveForm::end(); ?>
    </div>
</div>

frontend/views/site/profile.php
<?php
	use yii\helpers\Html;
    use yii\helpers\Url;
    use yii\grid\ActionColumn;
    use yii\grid\GridView;
	$this->title = 'My Profile';
	\yii\web\YiiAsset::register($this);
?>
<div class="row">
	<div class="col-md-3">
		<div class="boxed">
			<?=$this->render('summary');?>
		</div>
		<br>
	</div>
	<div class="col-md-9">
		<div class="boxed table-responsive">
			 <?= GridView::widget([
                'dataProvider' => $applications,
                // 'filterModel' => $searchModel,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

                    ['attribute'=>'job.title','label'=>'Job'],
                    ['attribute'=>'status_id','format'=>'raw','value'=>function($model){
                        return "<span data-toggle='tooltip' data-trigger='hover' data-placement='top' data-original-title='".$model->status->description."' class='badge badge-".$model->status->alert."'>".$model->status->name."</span>";
                    },'label'=>'Status'],
                    ['attribute'=>'status_id','format'=>'raw','value'=>function($model){
                        return $model->status_description ? $model->status_description : $model->status->description;
                    },'label'=>'Description'],

                    'date_applied:date',
                ],
            ]); ?>
		</div>
	</div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php
    use yii\bootstrap4\Html;
    use yii\bootstrap4\ActiveForm;
    $this->title = 'Request Password Reset';
    $this->params['breadcrumbs'][] = $this->title;
?>
<div class="col-lg-6 offset-lg-3">
    <div class="site-request-password-reset boxed">
        <h5><?= Html::encode($this->title) ?></h5>
        <hr class="hr-20">
        <p>Please fill out your email. A link to reset password will be sent there.</p>
        <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
            <?= $form->field($model, 'email')->textInput(['autofocus' => false]) ?>
            <div class="form-group float-right">
                <?= Html::submitButton('Send', ['class' => 'btn btn-primary btn-sm']) ?>
            </div>
            <span class="clearfix"></span>
        <?php ActiveForm::end(); ?>
    </div>
</div>

frontend/views/site/resendVerificationEmail.php
<?php
    use yii\bootstrap4\Html;
    use yii\bootstrap4\ActiveForm;
    $this->title = 'Resend verification email';
    $this->params['breadcrumbs'][] = $this->title;
?>
<div class="col-lg-6 offset-lg-3">
    <div class="site-resend-verification-email boxed">
        <h5><?= Html::encode($this->title) ?></h5>
        <hr class="hr-20">
        <p>Please fill out your email. A verification email will be sent there.</p>
        <?php $form = ActiveForm::begin(['id' => 'resend-verification-email-form']); ?>
        <?= $form->field($model, 'email')->textInput(['autofocus' => false]) ?>
        <div class="form-group float-right">
            <?= Html::submitButton('Send', ['class' => 'btn btn-primary btn-sm']) ?>
        </div>
        <span class="clearfix"></span>
        <?php ActiveForm::end(); ?>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php
use yii\bootstrap4\Html;
use yii\bootstrap4\ActiveForm;
$this->title = 'Reset Password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="col-lg-6 offset-lg-3">
    <div class="site-reset-password boxed">
        <h5><?= Html::encode($this->title) ?></h5>
        <hr class="hr-20">
        <p>Please choose your new password:</p>
        <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
            <?= $form->field($model, 'password')->passwordInput(['autofocus' => false]) ?>
            <div class="form-group float-right">
                <?= Html::submitButton('Save', ['class' => 'btn btn-primary btn-sm']) ?>
            </div>
            <span class="clearfix"></span>
        <?php ActiveForm::end(); ?>
    </div>
</div>

frontend/views/site/signup.php
<?php
use yii\bootstrap4\Html;
use yii\bootstrap4\ActiveForm;
$this->title = 'Register';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="col-lg-6 offset-3">
    <div class="site-signup boxed">
        <h5><?= Html::encode($this->title) ?></h5>
        <hr class="hr-20">
        <p>Please fill out the following fields to signup:</p>
        <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
            <?= $form->field($model, 'firstname')->textInput() ?>
            <?= $form->field($model, 'lastname')->textInput() ?>
            <?= $form->field($model, 'email') ?>
            <?= $form->field($model, 'phone') ?>
            <?= $form->field($model, 'password')->passwordInput() ?>
            <div class="form-group float-right">
                <?= Html::submitButton('Signup', ['class' => 'btn btn-primary btn-sm', 'name' => 'signup-button']) ?>
            </div>
            <span class="clearfix"></span>
        <?php ActiveForm::end(); ?>
    </div>
</div>

frontend/views/site/summary.php
<?php
	$user = \Yii::$app->user->identity;
	use yii\helpers\Html;
?>
<center>
	<div class="profile-picture">
		<?=Html::img('/uploads/'.$user->avatar,['width'=>'80']);?>
	</div>
	<hr class="hr-20">
	<?=$user->firstname.' '.$user->lastname.' '.$user->surname;?>
	<hr class="hr-20">
	<?=Html::a('Update',['site/update'],['class'=>'btn btn-primary btn-sm col-md-12']);?>
</center>

frontend/views/site/update.php
<?php
	use yii\helpers\Html;
	use yii\widgets\DetailView;
	$this->title = 'Update Profile';
	\yii\web\YiiAsset::register($this);
	$user = \Yii::$app->user->identity;
	use yii\widgets\ActiveForm;
?>
<div class="row">
	<div class="col-md-3">
		<div class="boxed">
			<?=$this->render('summary',['user'=>$user]);?>
		</div>
		<br>
	</div>
	<div class="col-md-9">
		<div class="boxed">
			<?php $form = ActiveForm::begin(); ?>
				<?=$form->field($user,'surname');?>
				<?=$form->field($user,'firstname');?>
				<?=$form->field($user,'lastname');?>
				<?=$form->field($user,'phone');?>
				<label>Profile Picture</label>
				<?=$form->field($user,'avatar')->fileInput(['name'=>'avatar'])->label(false);?>
				<hr class="hr-20">
				<div class="form-group float-right">
					<button class="btn btn-success btn-sm">Save</button>
				</div>
				<span class="clearfix"></span>
			<?php ActiveForm::end(); ?>
		</div>
	</div>
</div>